config/routes.rb
Rails.application.routes.draw do
  resources :monthly_condominium_expenses
  resources :corporate_owners
  resources :owners
  resources :renters
  root 'home#index'
  resources :apartments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/renter.rb
class Renter < ApplicationRecord
	has_one :apartment, required: false
	validates_presence_of :name, :cell_phone
	validates_presence_of :spouse_name, :if => lambda{ |object| object.spouse_cell_phone.present? }
	validates_presence_of :spouse_cell_phone, :if => lambda{ |object| object.spouse_name.present? }
	validates_format_of :cell_phone, :with => /(\(\d{2}\)\s)(\d{4,5}\-\d{4})/
	validates_format_of :spouse_cell_phone, :with => /(\(\d{2}\)\s)(\d{4,5}\-\d{4})/, :if => lambda{ |object| object.spouse_cell_phone.present? }
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  before_action :set_renter, only: [:show, :edit, :update, :destroy]

  # GET /renters
  # GET /renters.json
  def index
    @renters = Renter.all
  end

  # GET /renters/1
  # GET /renters/1.json
  def show
  end

  # GET /renters/new
  def new
    @renter = Renter.new
  end

  # GET /renters/1/edit
  def edit
  end

  # POST /renters
  # POST /renters.json
  def create
    @renter = Renter.new(renter_params)

    respond_to do |format|
      if @renter.save
        format.html { redirect_to renters_url, notice: 'Renter was successfully created.' }
        format.json { render :show, status: :created, location: @renter }
      else
        format.html { render :new }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renters/1
  # PATCH/PUT /renters/1.json
  def update
    respond_to do |format|
      if @renter.update(renter_params)
        format.html { redirect_to renters_url, notice: 'Renter was successfully updated.' }
        format.json { render :show, status: :ok, location: @renter }
      else
        format.html { render :edit }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter.destroy
    respond_to do |format|
      format.html { redirect_to renters_url, notice: 'Renter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renter
      @renter = Renter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def renter_params
      params.require(:renter).permit(:name, :spouse_name, :cell_phone, :spouse_cell_phone)
    end
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/renters/_form.html.erb
<%= bootstrap_form_for(@renter, layout: :horizontal, label_errors: true) do |f| %>

  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :cell_phone, :class => 'form-control phone_with_ddd' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :spouse_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :spouse_cell_phone, :class => 'form-control phone_with_ddd' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                renters_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/renters/edit.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/renters/index.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cell_phone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @renters.each do |renter| %>
      <tr>
        <td><%= link_to renter.name, renter_path(renter) %></td>
        <td><%= renter.cell_phone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_renter_path(renter), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      renter_path(renter),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_renter_path,
            :class => 'btn btn-primary' %>

app/views/renters/new.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/renters/show.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @renter.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:spouse_name) %>:</strong></dt>
  <dd><%= @renter.spouse_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cell_phone) %>:</strong></dt>
  <dd><%= @renter.cell_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:spouse_cell_phone) %>:</strong></dt>
  <dd><%= @renter.spouse_cell_phone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              renters_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_renter_path(@renter), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              renter_path(@renter),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>