config/routes.rb
Rails.application.routes.draw do
  resources :monthly_condominium_expenses
  resources :corporate_owners
  resources :owners
  resources :renters
  root 'home#index'
  resources :apartments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord
	has_many :apartments, :as => :ownable
	validates_presence_of :name, :cell_phone
	validates_presence_of :spouse_name, :if => lambda{ |object| object.spouse_cell_phone.present? }
	validates_presence_of :spouse_cell_phone, :if => lambda{ |object| object.spouse_name.present? }
	validates_format_of :cell_phone, :with => /(\(\d{2}\)\s)(\d{4,5}\-\d{4})/
	validates_format_of :spouse_cell_phone, :with => /(\(\d{2}\)\s)(\d{4,5}\-\d{4})/, :if => lambda{ |object| object.spouse_cell_phone.present? }
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to owners_url, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to owners_url, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def owner_params
      params.require(:owner).permit(:name, :spouse_name, :cell_phone, :spouse_cell_phone)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= bootstrap_form_for(@owner, layout: :horizontal, label_errors: true) do |f| %>

  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :spouse_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :cell_phone, :class => 'form-control phone_with_ddd' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :spouse_cell_phone, :class => 'form-control phone_with_ddd' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                owners_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/owners/edit.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/owners/index.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(:count => 2).titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cell_phone) %></th>
      <th><%= Apartment.human_attribute_name(:occupied) %></th>
      <th><%= model_class.human_attribute_name(:apartments) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= link_to owner.name, owner_path(owner) %></td>
        <td><%= owner.cell_phone %></td>
        <td><%= owner.apartments.occupied.join(", ") %></td>
        <td><%= owner.apartments.numbers.join(", ") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_owner_path(owner), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      owner_path(owner),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_owner_path,
            :class => 'btn btn-primary' %>

app/views/owners/new.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/owners/show.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @owner.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:spouse_name) %>:</strong></dt>
  <dd><%= @owner.spouse_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cell_phone) %>:</strong></dt>
  <dd><%= @owner.cell_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:spouse_cell_phone) %>:</strong></dt>
  <dd><%= @owner.spouse_cell_phone %></dd>
  <dt><strong><%= Apartment.human_attribute_name(:occupied) %>:</strong></dt>
  <dd><%= @owner.apartments.occupied.join(", ") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apartments) %>:</strong></dt>
  <dd><%= @owner.apartments.numbers.join(", ") %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              owners_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_owner_path(@owner), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              owner_path(@owner),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>