config/routes.rb
Rails.application.routes.draw do
  resources :monthly_condominium_expenses
  resources :corporate_owners
  resources :owners
  resources :renters
  root 'home#index'
  resources :apartments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
	belongs_to :ownable, polymorphic: true
	belongs_to :renter, optional: true

	scope :occupied, -> { where(:ocuppied => true).pluck(:number).flatten }
	scope :numbers, -> { pluck(:number).flatten }

	# Use :to_global_id to populate the form
	def ownable_gid
	  ownable&.to_global_id
	end

	# Set the :bloggable from a Global ID (handles the form submission)
	def ownable_gid=(gid)
	  self.ownable = GlobalID::Locator.locate gid
	end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :set_ownables, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to apartments_url, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to apartments_url, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    def set_ownables
      @ownables = Owner.all + CorporateOwner.all
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:number, :floor, :renter_id, :ownable_gid, :ocuppied)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= bootstrap_form_for(@apartment, layout: :horizontal, label_errors: true) do |f| %>

  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :number, :readonly => true, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :floor, :readonly => true, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.collection_select :renter_id, Renter.all, :id, :name, :include_blank => t('helpers.select_option') %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.collection_select(:ownable_gid, @ownables, :to_global_id, :name) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <div class="form-group row">
        <label class="col-form-label col-sm-2"><%= t('helpers.labels.ocuppied') %></label>
        <div class="col-sm-10">
          <%= f.radio_button :ocuppied, true, label: t('helpers.labels.positive') %>
          <%= f.radio_button :ocuppied, false, label: t('helpers.labels.negative') %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                apartments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/apartments/edit.html.erb
<%- model_class = Apartment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apartments/index.html.erb
<%- model_class = Apartment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:floor) %></th>
      <th><%= model_class.human_attribute_name(:renter_id) %></th>
      <th><%= model_class.human_attribute_name(:ownable_gid) %></th>
      <th><%= model_class.human_attribute_name(:ocuppied) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= link_to apartment.number, apartment_path(apartment) %></td>
        <td><%= apartment.floor %></td>
        <td><%= apartment.renter.name if apartment.renter.present? %></td>
        <td><%= apartment.ownable.name %></td>
        <td><%= t apartment.ocuppied?.to_s %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_apartment_path(apartment), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/apartments/new.html.erb
<%- model_class = Apartment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apartments/show.html.erb
<%- model_class = Apartment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @apartment.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:floor) %>:</strong></dt>
  <dd><%= @apartment.floor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:renter_id) %>:</strong></dt>
  <dd><%= @apartment.renter.name if @apartment.renter.present? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ownable_gid) %>:</strong></dt>
  <dd><%= @apartment.ownable.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ocuppied) %>:</strong></dt>
  <dd><%= t @apartment.ocuppied?.to_s %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              apartments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_apartment_path(@apartment), :class => 'btn btn-default' %>