config/routes.rb
Rails.application.routes.draw do
  resources :monthly_condominium_expenses
  resources :corporate_owners
  resources :owners
  resources :renters
  root 'home#index'
  resources :apartments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Residencial Senna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Residencial Senna", root_path, class: "navbar-brand" %>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t("breadcrumbs.application.registrations") %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to Apartment.model_name.human.pluralize.titleize, apartments_path %></li>
              <li><%= link_to Renter.model_name.human.pluralize.titleize, renters_path %></li>
              <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("breadcrumbs.application.owners") %></a>
                <ul class="dropdown-menu">
                    <li><%= link_to Owner.model_name.human(:count => 2).pluralize.titleize, owners_path %></li>
                    <li><%= link_to CorporateOwner.model_name.human(:count => 2).pluralize.titleize, corporate_owners_path %></li>
                </ul>
            </ul>
          </li>
          <li><%= link_to MonthlyCondominiumExpense.model_name.human(:count => 2).titleize,monthly_condominium_expenses_path %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
    </div>
  </div> 
</html>